# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EIxufCEieF1iTlIL0skjufsy-NKbR5oj
"""

#========= Equalizador gráfico de áudio de 5 bandas — trabalho de PDS =========#

"""
Implementação alinhada ao Capítulo 9.1 da apostila:
- áudio reproduzido a partir de arquivo;
- fs = 44 100 Hz;
- cinco filtros FIR por janelamento de Hamming;
- bandas separadas pelos pontos médios entre 100, 330, 1000, 3300 e 10000 Hz;
- ganhos em dB, convertidos por A = 10^(AdB/20);
- recomposição pela soma das cinco saídas filtradas e ponderadas;
- analisador em tempo real com dez barras espectrais;
- exportação de WAV equalizado e de gráfico de respostas em frequência.
"""

#==============================================================================#
#================================ Bibliotecas =================================#
#==============================================================================#

import math
import queue
import threading
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path
from typing import Optional

import numpy as np
import soundfile as sf
from scipy import signal

try:
    import sounddevice as sd
except ImportError:
    sd = None

import tkinter as tk
from tkinter import filedialog, messagebox, ttk

from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure


#==============================================================================#
#========================= 1.0 Parâmetros do trabalho =========================#
#==============================================================================#

FS = 44_100 #frequência de amostragem
NUM_TAPS = 2_001  #número de coeficientes do filtro
FFT_SIZE = 4_096 #número de pontos da Transformada Rápida de Fourier
BLOCK_SIZE = 1_024 #amostras de áudio que o programa processa por vez durante a reprodução
MIN_DB = -80.0 #menor nível mostrado no gráfico de espectro

CENTRAL_FREQUENCIES_HZ = np.array([100.0, 330.0, 1_000.0, 3_300.0, 10_000.0])
# Pontos médios exigidos entre as frequências centrais
CUTOFFS_HZ = (CENTRAL_FREQUENCIES_HZ[:-1] + CENTRAL_FREQUENCIES_HZ[1:]) / 2.0
# frequências de corte que separam as cinco bandas do equalizador [215, 665, 2150, 6650] Hz


#---------- 1.1 Dez faixas distribuídas para o analisador de espectro ----------
ANALYZER_EDGES_HZ = np.array(
    [20, 50, 100, 200, 400, 800, 1_600, 3_200, 6_400, 12_800, FS / 2],
    dtype=float,
)
ANALYZER_LABELS = [
    "20–50",
    "50–100",
    "100–200",
    "200–400",
    "400–800",
    "0,8–1,6k",
    "1,6–3,2k",
    "3,2–6,4k",
    "6,4–12,8k",
    "12,8–22k",
]

#----------------- 1.2 Descrição de cada banda do equalizador ------------------
@dataclass(frozen=True)
class BandInfo:
    """Metadados de uma banda do equalizador."""

    label: str
    kind: str
    low_hz: float
    high_hz: float


BANDS = (
    BandInfo("100 Hz", "Passa-baixa", 0.0, CUTOFFS_HZ[0]),
    BandInfo("330 Hz", "Passa-faixa", CUTOFFS_HZ[0], CUTOFFS_HZ[1]),
    BandInfo("1 kHz", "Passa-faixa", CUTOFFS_HZ[1], CUTOFFS_HZ[2]),
    BandInfo("3,3 kHz", "Passa-faixa", CUTOFFS_HZ[2], CUTOFFS_HZ[3]),
    BandInfo("10 kHz", "Passa-alta", CUTOFFS_HZ[3], FS / 2),
)


#==============================================================================#
#==== 2.0 Projeto FIR por janelamento — implementação explícita da teoria =====#
#==============================================================================#

def ideal_lowpass(cutoff_hz: float, fs: int, n: np.ndarray) -> np.ndarray:
    """Resposta ao impulso ideal de um passa-baixa centrado em n = 0.

    Para wc = 2*pi*fc/fs:
        h_i[n] = sin(wc*n)/(pi*n), n != 0
        h_i[0] = wc/pi
    """
    if fs <= 0:
        raise ValueError("A frequência de amostragem deve ser maior que zero.")

    if not 0.0 < cutoff_hz < fs / 2:
        raise ValueError("A frequência de corte deve estar entre 0 e fs/2.")

    wc = 2.0 * np.pi * cutoff_hz / fs

    h = np.empty_like(n, dtype=np.float64)

    at_zero = n == 0
    h[at_zero] = wc / np.pi

    nz = ~at_zero
    h[nz] = np.sin(wc * n[nz]) / (np.pi * n[nz])

    return h


def design_equalizer_filters(
    fs: int = FS,
    num_taps: int = NUM_TAPS,
) -> tuple[np.ndarray, np.ndarray]:
    """Cria os cinco FIR de fase linear, com janela de Hamming.

    A construção é complementar:
      h0 = LP(215 Hz)
      h1 = LP(665)  - LP(215)
      h2 = LP(2150) - LP(665)
      h3 = LP(6650) - LP(2150)
      h4 = delta - LP(6650)

    Por consequência, sum_i h_i[n] = delta[n-K].
    """
    if num_taps < 101 or num_taps % 2 == 0:
        raise ValueError("num_taps deve ser ímpar e maior ou igual a 101.")

    k = num_taps // 2
    n = np.arange(-k, k + 1, dtype=np.float64)

    # Janela de Hamming aplicada aos filtros FIR.
    window = np.hamming(num_taps)

    def windowed_lp(fc_hz: float) -> np.ndarray:
        """Cria um passa-baixas ideal e aplica a janela de Hamming."""
        return ideal_lowpass(fc_hz, fs, n) * window

    # Passa-baixa utilizados para criar as cinco bandas complementares.
    lp_215 = windowed_lp(CUTOFFS_HZ[0])
    lp_665 = windowed_lp(CUTOFFS_HZ[1])
    lp_2150 = windowed_lp(CUTOFFS_HZ[2])
    lp_6650 = windowed_lp(CUTOFFS_HZ[3])

    # Impulso unitário deslocado para a posição central do filtro FIR.
    delta = np.zeros(num_taps, dtype=np.float64)
    delta[k] = 1.0

    filters = np.vstack(
        (
            lp_215,
            lp_665 - lp_215,
            lp_2150 - lp_665,
            lp_6650 - lp_2150,
            delta - lp_6650,
        )
    )

    # Verificação numérica da propriedade complementar explicada acima.
    if not np.allclose(filters.sum(axis=0), delta, rtol=0.0, atol=1e-12):
        raise RuntimeError("Os filtros deixaram de formar uma partição complementar.")

    return filters, n.astype(int)


def db_to_linear(db: np.ndarray | float) -> np.ndarray | float:
    """Converte ganho em dB para ganho de amplitude linear."""
    gain = np.power(10.0, np.asarray(db, dtype=np.float64) / 20.0)

    if np.ndim(db) == 0:
        return float(gain)

    return gain


def magnitude_db(values: np.ndarray, floor_db: float = MIN_DB) -> np.ndarray:
    """Magnitude em dB, limitada inferiormente para facilitar visualização."""
    floor_linear = 10.0 ** (floor_db / 20.0)
    return 20.0 * np.log10(np.maximum(np.abs(values), floor_linear))


def resample_to_44k1(audio: np.ndarray, original_fs: int) -> np.ndarray:
    """Reamostra o áudio para 44,1 kHz, quando necessário."""
    if original_fs <= 0:
        raise ValueError("A frequência de amostragem original deve ser maior que zero.")

    if original_fs == FS:
        return audio

    ratio = Fraction(FS, original_fs).limit_denominator()

    return signal.resample_poly(
        audio,
        ratio.numerator,
        ratio.denominator,
        axis=0,
    )


def filter_audio_into_bands(audio: np.ndarray, filters: np.ndarray) -> np.ndarray:
    """Filtra um áudio estéreo/mono por cada FIR.

    Retorna um vetor com formato:
        [5, amostras + num_taps - 1, canais]

    A convolução é calculada por FFT antes da reprodução. Dessa forma, durante
    o play os sliders alteram somente a soma ponderada das cinco bandas, o que
    permite resposta imediata mesmo com FIRs de 2001 coeficientes.
    """
    if audio.ndim != 2:
        raise ValueError("audio deve ter forma [amostras, canais].")

    filtered = []

    for h in filters:
        # O modo "full" mantém o atraso K e a cauda do FIR.
        # Assim, a resposta é compatível com a realização causal do filtro.
        y = signal.fftconvolve(audio, h[:, None], mode="full", axes=0)

        filtered.append(y.astype(np.float32, copy=False))

    return np.stack(filtered, axis=0)


#==============================================================================#
#=========================== 3.0 Aplicação Gráfica ============================#
#==============================================================================#


class ScrollableControls(ttk.Frame):
    """Painel vertical com barra de rolagem para os controles da interface."""

    def __init__(self, parent: tk.Misc, width: int = 320) -> None:
        super().__init__(parent)

        self.canvas = tk.Canvas(
            self,
            width=width,
            highlightthickness=0,
            borderwidth=0,
        )
        self.scrollbar = ttk.Scrollbar(
            self,
            orient=tk.VERTICAL,
            command=self.canvas.yview,
        )
        self.content = ttk.Frame(self.canvas, padding=(0, 0, 12, 0))

        self.content_window = self.canvas.create_window(
            (0, 0),
            window=self.content,
            anchor=tk.NW,
        )

        self.canvas.configure(yscrollcommand=self.scrollbar.set)

        self.canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        self.scrollbar.pack(side=tk.RIGHT, fill=tk.Y)

        self.content.bind("<Configure>", self._update_scroll_region)
        self.canvas.bind("<Configure>", self._update_content_width)

    def _update_scroll_region(self, _event=None) -> None:
        """Atualiza a região que pode ser percorrida pela barra de rolagem."""
        self.canvas.configure(scrollregion=self.canvas.bbox("all"))

    def _update_content_width(self, event) -> None:
        """Mantém a largura dos controles igual à largura visível do painel."""
        self.canvas.itemconfigure(self.content_window, width=event.width)

class EqualizerApp:
    """Interface Tkinter do equalizador e do analisador de espectro."""

    def __init__(self, root: tk.Tk) -> None:
        self.root = root
        self.root.title("Equalizador FIR de 5 bandas — Processamento Digital de Sinais")
        self.root.minsize(1180, 700)

        self.filters, self.n = design_equalizer_filters()
        self.group_delay = len(self.n) // 2
        self.freqs_hz, self.filter_response = self._calculate_filter_responses()

        self.audio_path: Optional[Path] = None
        self.original_audio: Optional[np.ndarray] = None
        self.band_audio: Optional[np.ndarray] = None
        self.play_position = 0
        self.stream: Optional["sd.OutputStream"] = None
        self._state_lock = threading.Lock()
        # Valores numéricos separados das variáveis Tkinter. A callback de áudio
        # executa em outra thread e não deve acessar widgets/DoubleVar diretamente.
        self._gains_linear = np.ones(5, dtype=np.float64)
        self._preamp_linear = 1.0
        self._analysis_queue: queue.Queue[np.ndarray] = queue.Queue(maxsize=6)
        self._analysis_samples = np.zeros(FFT_SIZE, dtype=np.float32)
        self._bar_db = np.full(10, MIN_DB, dtype=np.float64)
        self._response_update_pending = False

        self.gain_vars = [tk.DoubleVar(value=0.0) for _ in range(5)]
        self.preamp_var = tk.DoubleVar(value=0.0)
        self.file_var = tk.StringVar(value="Nenhum áudio carregado")
        self.status_var = tk.StringVar(value="Carregue um arquivo de áudio para iniciar.")
        self.delay_var = tk.StringVar(value=f"Atraso FIR: {self.group_delay / FS * 1_000:.1f} ms")

        self._build_ui()
        self._refresh_response_plot()
        self._schedule_analyzer_update()

    #----------------------- 3.1 Construção da interface -----------------------
    def _build_ui(self) -> None:
        outer = ttk.Frame(self.root, padding=10)
        outer.pack(fill=tk.BOTH, expand=True)

        controls_panel = ScrollableControls(outer, width=320)
        controls_panel.pack(side=tk.LEFT, fill=tk.BOTH)

        controls = controls_panel.content

        plots = ttk.Frame(outer)
        plots.pack(side=tk.RIGHT, fill=tk.BOTH, expand=True)

        ttk.Label(controls, text="Equalizador gráfico", font=("TkDefaultFont", 13, "bold")).pack(anchor=tk.W)
        ttk.Label(
            controls,
            text="FIR por janela de Hamming\nfs = 44,1 kHz | 2K+1 = 2001",
            justify=tk.LEFT,
        ).pack(anchor=tk.W, pady=(2, 12))

        sliders = ttk.Frame(controls)
        sliders.pack(fill=tk.X, pady=(0, 8))
        for idx, band in enumerate(BANDS):
            column = ttk.Frame(sliders)
            column.grid(row=0, column=idx, padx=3)
            value_label = ttk.Label(column, text="0,0 dB", anchor=tk.CENTER)
            value_label.pack(fill=tk.X)
            scale = tk.Scale(
                column,
                from_=12.0,
                to=-12.0,
                resolution=0.5,
                orient=tk.VERTICAL,
                length=255,
                showvalue=False,
                variable=self.gain_vars[idx],
                command=lambda _value, i=idx, label=value_label: self._on_band_gain_change(i, label),
            )
            scale.pack()
            ttk.Label(column, text=band.label, anchor=tk.CENTER).pack(fill=tk.X)
            ttk.Label(column, text=band.kind, anchor=tk.CENTER, font=("TkDefaultFont", 7)).pack(fill=tk.X)

        preamp_frame = ttk.LabelFrame(controls, text="Pré-amplificação", padding=7)
        preamp_frame.pack(fill=tk.X, pady=(7, 8))
        self.preamp_value_label = ttk.Label(preamp_frame, text="0,0 dB", width=8)
        self.preamp_value_label.pack(side=tk.RIGHT)
        preamp = tk.Scale(
            preamp_frame,
            from_=-18.0,
            to=0.0,
            resolution=0.5,
            orient=tk.HORIZONTAL,
            showvalue=False,
            variable=self.preamp_var,
            command=lambda _value: self._on_preamp_change(),
        )
        preamp.pack(side=tk.LEFT, fill=tk.X, expand=True)
        ttk.Label(
            controls,
            text="Use a pré-amplificação para evitar clipping\nquando houver ganho positivo em uma ou mais bandas.",
            justify=tk.LEFT,
            wraplength=280,
        ).pack(anchor=tk.W, pady=(0, 9))

        file_frame = ttk.LabelFrame(controls, text="Arquivo de áudio", padding=7)
        file_frame.pack(fill=tk.X, pady=(2, 8))
        ttk.Label(file_frame, textvariable=self.file_var, wraplength=285).pack(anchor=tk.W, pady=(0, 5))
        ttk.Button(file_frame, text="Carregar áudio", command=self.load_audio).pack(fill=tk.X)

        transport = ttk.LabelFrame(controls, text="Reprodução", padding=7)
        transport.pack(fill=tk.X, pady=(0, 8))
        ttk.Button(transport, text="▶  Reproduzir / continuar", command=self.play).grid(row=0, column=0, sticky="ew", padx=(0, 3))
        ttk.Button(transport, text="❚❚  Pausar", command=self.pause).grid(row=0, column=1, sticky="ew", padx=(3, 0))
        ttk.Button(transport, text="■  Parar", command=self.stop).grid(row=1, column=0, columnspan=2, sticky="ew", pady=(5, 0))
        transport.columnconfigure(0, weight=1)
        transport.columnconfigure(1, weight=1)

        export_frame = ttk.LabelFrame(controls, text="Saídas para a entrega", padding=7)
        export_frame.pack(fill=tk.X, pady=(0, 8))
        ttk.Button(export_frame, text="Salvar WAV equalizado", command=self.export_equalized_wav).pack(fill=tk.X)
        ttk.Button(export_frame, text="Salvar gráfico das respostas", command=self.export_transfer_figure).pack(fill=tk.X, pady=(5, 0))
        ttk.Button(export_frame, text="Salvar coeficientes FIR (CSV)", command=self.export_coefficients).pack(fill=tk.X, pady=(5, 0))

        ttk.Separator(controls).pack(fill=tk.X, pady=(8, 5))
        ttk.Label(controls, textvariable=self.delay_var).pack(anchor=tk.W)
        ttk.Label(controls, textvariable=self.status_var, wraplength=290, justify=tk.LEFT).pack(anchor=tk.W, pady=(6, 0))

        #----- 3.2 Figura: resposta dos filtros + analisador de dez barras -----
        self.figure = Figure(figsize=(10.0, 6.5), dpi=100)
        self.ax_response = self.figure.add_subplot(2, 1, 1)
        self.ax_analyzer = self.figure.add_subplot(2, 1, 2)
        self.figure.tight_layout(pad=2.2)
        self.canvas = FigureCanvasTkAgg(self.figure, master=plots)
        self.canvas.get_tk_widget().pack(fill=tk.BOTH, expand=True)

        self.bars = self.ax_analyzer.bar(np.arange(10), np.zeros(10), width=0.78)
        self.ax_analyzer.set_ylim(MIN_DB, 0)
        self.ax_analyzer.set_xlim(-0.6, 9.6)
        self.ax_analyzer.set_xticks(np.arange(10), ANALYZER_LABELS, rotation=25, ha="right")
        self.ax_analyzer.set_ylabel("Nível (dBFS)")
        self.ax_analyzer.set_title("Analisador de espectro — 10 bandas")
        self.ax_analyzer.grid(axis="y", alpha=0.3)

        self.root.protocol("WM_DELETE_WINDOW", self.on_close)

    #------------------------- 3.3 Filtros e Gráficos --------------------------
    def _calculate_filter_responses(self) -> tuple[np.ndarray, np.ndarray]:
        responses = []
        freqs = None
        for h in self.filters:
            f, H = signal.freqz(h, worN=16_384, fs=FS)
            freqs = f
            responses.append(H)
        return np.asarray(freqs), np.asarray(responses)

    def _current_linear_gains(self) -> np.ndarray:
        """Retorna uma cópia thread-safe dos ganhos lineares atuais."""
        with self._state_lock:
            return self._gains_linear.copy()

    def _current_preamp(self) -> float:
        with self._state_lock:
            return float(self._preamp_linear)

    def _refresh_response_plot(self) -> None:
        self._response_update_pending = False
        gains = self._current_linear_gains()
        H_current = np.sum(gains[:, None] * self.filter_response, axis=0)
        H_inactive = np.sum(self.filter_response, axis=0)

        ax = self.ax_response
        ax.clear()
        visible = self.freqs_hz >= 20.0

        for idx, band in enumerate(BANDS):
            ax.semilogx(
                self.freqs_hz[visible],
                magnitude_db(self.filter_response[idx, visible]),
                linewidth=1.0,
                label=f"{band.label}: {band.low_hz:.0f}–{band.high_hz:.0f} Hz",
            )

        ax.semilogx(
            self.freqs_hz[visible],
            magnitude_db(H_inactive[visible]),
            linestyle="--",
            linewidth=1.4,
            label="Equalizador inativo (todos em 0 dB)",
        )
        ax.semilogx(
            self.freqs_hz[visible],
            magnitude_db(H_current[visible]),
            linewidth=2.0,
            label="Equalizador — ganhos atuais",
        )
        for cutoff in CUTOFFS_HZ:
            ax.axvline(cutoff, linestyle=":", linewidth=0.8)

        ax.set_xlim(20, FS / 2)
        ax.set_ylim(-75, 15)
        ax.set_xlabel("Frequência (Hz)")
        ax.set_ylabel("Magnitude (dB)")
        ax.set_title("Respostas em frequência dos filtros FIR e do equalizador")
        ax.grid(which="both", alpha=0.25)
        ax.legend(fontsize=8, ncol=2, loc="lower left")
        self.canvas.draw_idle()

    def _request_response_refresh(self) -> None:
        if not self._response_update_pending:
            self._response_update_pending = True
            self.root.after(60, self._refresh_response_plot)

    def _on_band_gain_change(self, index: int, value_label: ttk.Label) -> None:
        gain_db = self.gain_vars[index].get()
        with self._state_lock:
            self._gains_linear[index] = float(db_to_linear(gain_db))
        value_label.config(text=f"{gain_db:.1f} dB".replace(".", ","))
        self._request_response_refresh()

    def _on_preamp_change(self) -> None:
        preamp_db = self.preamp_var.get()
        with self._state_lock:
            self._preamp_linear = float(db_to_linear(preamp_db))
        self.preamp_value_label.config(text=f"{preamp_db:.1f} dB".replace(".", ","))

    #-------------------------------- 3.3 Áudio --------------------------------
    def load_audio(self) -> None:
        self.stop()
        path_text = filedialog.askopenfilename(
            title="Selecione o áudio",
            filetypes=[
                ("Áudios compatíveis", "*.wav *.flac *.ogg *.aiff *.aif"),
                ("WAV", "*.wav"),
                ("Todos os arquivos", "*.*"),
            ],
        )
        if not path_text:
            return

        try:
            path = Path(path_text)
            self.status_var.set("Lendo arquivo e calculando as cinco bandas FIR...")
            self.root.update_idletasks()

            audio, original_fs = sf.read(path, dtype="float32", always_2d=True)
            if audio.size == 0:
                raise ValueError("O arquivo não possui amostras de áudio.")

            # Mantém mono/estéreo; para arquivos multicanal, usa os dois primeiros.
            if audio.shape[1] > 2:
                audio = audio[:, :2]

            if original_fs != FS:
                audio = resample_to_44k1(audio, original_fs).astype(np.float32, copy=False)
                resample_message = f"Reamostrado de {original_fs} Hz para 44 100 Hz."
            else:
                resample_message = "Áudio já está em 44 100 Hz."

            # Estimativa de memória: 5 sinais filtrados, em float32.
            estimated_mb = 5 * (audio.shape[0] + NUM_TAPS - 1) * audio.shape[1] * 4 / (1024**2)
            if estimated_mb > 1_000:
                ok = messagebox.askyesno(
                    "Arquivo grande",
                    f"A pré-filtragem usará aproximadamente {estimated_mb:.0f} MB de memória.\n"
                    "Deseja continuar?",
                )
                if not ok:
                    self.status_var.set("Carregamento cancelado.")
                    return

            self.original_audio = audio
            self.band_audio = filter_audio_into_bands(audio, self.filters)
            self.audio_path = path
            self.play_position = 0
            self._analysis_samples.fill(0.0)
            self._bar_db.fill(MIN_DB)
            self.file_var.set(f"{path.name}\n{audio.shape[0] / FS:.1f} s | {audio.shape[1]} canal(is)")
            self.status_var.set(
                f"Pronto. {resample_message} Ajuste os sliders e reproduza."
            )
        except Exception as exc:
            self.original_audio = None
            self.band_audio = None
            self.audio_path = None
            self.file_var.set("Nenhum áudio carregado")
            self.status_var.set("Falha ao carregar o áudio.")
            messagebox.showerror("Erro ao carregar", str(exc))

    def _mixed_chunk(self, start: int, frames: int) -> np.ndarray:
        """Retorna um trecho do áudio equalizado com os ganhos atuais."""
        if self.band_audio is None:
            return np.zeros((0, 1), dtype=np.float32)

        end = min(start + frames, self.band_audio.shape[1])
        with self._state_lock:
            gains = self._gains_linear.copy()
            preamp = float(self._preamp_linear)

        # [bandas] x [amostras] x [canais] -> [amostras] x [canais]
        chunk = np.tensordot(gains, self.band_audio[:, start:end, :], axes=(0, 0))
        return (preamp * chunk).astype(np.float32, copy=False)

    def _audio_callback(self, outdata: np.ndarray, frames: int, _time_info, status) -> None:
        if status:
            # A reprodução continua; o estado é exibido fora da callback.
            print(f"[Áudio] {status}")

        if self.band_audio is None:
            outdata.fill(0.0)
            raise sd.CallbackStop

        start = self.play_position
        chunk = self._mixed_chunk(start, frames)
        available = len(chunk)
        outdata.fill(0.0)
        if available:
            outdata[:available, :] = chunk
            mono = np.mean(chunk, axis=1)
            try:
                self._analysis_queue.put_nowait(mono.copy())
            except queue.Full:
                pass

        self.play_position += available
        if available < frames:
            raise sd.CallbackStop

    def _create_stream_if_needed(self) -> None:
        if self.band_audio is None:
            return
        if self.stream is None:
            self.stream = sd.OutputStream(
                samplerate=FS,
                blocksize=BLOCK_SIZE,
                channels=self.band_audio.shape[2],
                dtype="float32",
                callback=self._audio_callback,
                finished_callback=self._on_stream_finished,
            )

    def _on_stream_finished(self) -> None:
        # Não manipula widgets aqui: este callback pode ser chamado por outra thread.
        pass

    def play(self) -> None:
        if sd is None:
            messagebox.showerror(
                "Biblioteca ausente",
                "Instale a biblioteca sounddevice:\n\npip install sounddevice",
            )
            return
        if self.band_audio is None:
            messagebox.showwarning("Sem áudio", "Carregue um áudio antes de reproduzir.")
            return

        # Ao chegar ao fim, uma nova reprodução reinicia do início.
        if self.play_position >= self.band_audio.shape[1]:
            self.stop()
            self.play_position = 0

        try:
            self._create_stream_if_needed()
            assert self.stream is not None
            if not self.stream.active:
                self.stream.start()
            self.status_var.set("Reproduzindo. Os sliders atuam imediatamente sobre o áudio.")
        except Exception as exc:
            self.status_var.set("Não foi possível iniciar o dispositivo de áudio.")
            messagebox.showerror("Erro de reprodução", str(exc))

    def pause(self) -> None:
        if self.stream is not None and self.stream.active:
            self.stream.stop()
            self.status_var.set("Pausado.")

    def stop(self) -> None:
        if self.stream is not None:
            try:
                if self.stream.active:
                    self.stream.stop()
                self.stream.close()
            except Exception:
                pass
            self.stream = None
        self.play_position = 0
        while not self._analysis_queue.empty():
            try:
                self._analysis_queue.get_nowait()
            except queue.Empty:
                break

    #---------------------- 3.4 Analisador em tempo real -----------------------
    def _schedule_analyzer_update(self) -> None:
        self._update_analyzer()
        self.root.after(40, self._schedule_analyzer_update)

    def _update_analyzer(self) -> None:
        """Atualiza a FFT e as 10 barras no thread da interface gráfica."""
        received = False
        while True:
            try:
                chunk = self._analysis_queue.get_nowait()
            except queue.Empty:
                break
            received = True
            if len(chunk) >= FFT_SIZE:
                self._analysis_samples = chunk[-FFT_SIZE:].astype(np.float32, copy=False)
            else:
                self._analysis_samples = np.concatenate((self._analysis_samples[len(chunk):], chunk))

        if not received:
            return

        frame = self._analysis_samples * np.hanning(FFT_SIZE)
        X = np.fft.rfft(frame)
        freqs = np.fft.rfftfreq(FFT_SIZE, d=1.0 / FS)

        # Normalização aproximada para dBFS de amplitude.
        amplitude = np.abs(X) / (np.sum(np.hanning(FFT_SIZE)) / 2.0)
        current_db = np.empty(10, dtype=np.float64)
        for idx, (low, high) in enumerate(zip(ANALYZER_EDGES_HZ[:-1], ANALYZER_EDGES_HZ[1:])):
            selection = (freqs >= low) & (freqs < high)
            if np.any(selection):
                rms_band = np.sqrt(np.mean(amplitude[selection] ** 2))
                current_db[idx] = magnitude_db(np.array([rms_band]))[0]
            else:
                current_db[idx] = MIN_DB

        # Suavização visual para as barras não piscarem excessivamente.
        self._bar_db = 0.72 * self._bar_db + 0.28 * current_db
        for bar, level in zip(self.bars, self._bar_db):
            bar.set_height(max(MIN_DB, min(0.0, level)) - MIN_DB)
            bar.set_y(MIN_DB)
        self.canvas.draw_idle()

    #----------------------------- 3.5 Exportações -----------------------------
    def _full_equalized_audio(self) -> np.ndarray:
        if self.band_audio is None:
            raise RuntimeError("Nenhum áudio foi carregado.")
        gains = self._current_linear_gains()
        preamp = self._current_preamp()
        return (preamp * np.tensordot(gains, self.band_audio, axes=(0, 0))).astype(np.float32)

    def export_equalized_wav(self) -> None:
        if self.band_audio is None:
            messagebox.showwarning("Sem áudio", "Carregue um áudio antes de exportar.")
            return
        initial_name = "audio_equalizado.wav"
        if self.audio_path is not None:
            initial_name = f"{self.audio_path.stem}_equalizado.wav"

        path_text = filedialog.asksaveasfilename(
            title="Salvar áudio equalizado",
            defaultextension=".wav",
            initialfile=initial_name,
            filetypes=[("WAV", "*.wav")],
        )
        if not path_text:
            return

        try:
            y = self._full_equalized_audio()
            peak = float(np.max(np.abs(y)))
            if peak > 0.999:
                normalize = messagebox.askyesno(
                    "Risco de clipping",
                    f"O pico atual é {peak:.2f}, acima do limite digital de 1,0.\n\n"
                    "Deseja normalizar o arquivo exportado para -0,1 dBFS?\n"
                    "(Recomendado; reduza a pré-amplificação para evitar isso.)",
                )
                if normalize:
                    y = y * (0.9886 / peak)
                else:
                    y = np.clip(y, -1.0, 1.0)

            sf.write(path_text, y, FS, subtype="PCM_16")
            self.status_var.set(f"WAV equalizado salvo em: {Path(path_text).name}")
        except Exception as exc:
            messagebox.showerror("Erro ao exportar WAV", str(exc))

    def _build_transfer_figure(self) -> Figure:
        """Monta uma figura própria para anexar ao relatório."""
        fig = Figure(figsize=(12, 6.5), dpi=160)
        ax = fig.add_subplot(1, 1, 1)
        visible = self.freqs_hz >= 20.0
        inactive = np.sum(self.filter_response, axis=0)
        current = np.sum(self._current_linear_gains()[:, None] * self.filter_response, axis=0)

        for idx, band in enumerate(BANDS):
            ax.semilogx(
                self.freqs_hz[visible],
                magnitude_db(self.filter_response[idx, visible]),
                linewidth=1.0,
                label=f"{band.label}: {band.low_hz:.0f}–{band.high_hz:.0f} Hz",
            )
        ax.semilogx(
            self.freqs_hz[visible],
            magnitude_db(inactive[visible]),
            linestyle="--",
            linewidth=1.5,
            label="Equalizador inativo (todos os ganhos em 0 dB)",
        )
        ax.semilogx(
            self.freqs_hz[visible],
            magnitude_db(current[visible]),
            linewidth=2.0,
            label="Equalizador com os ganhos atuais",
        )
        for cutoff in CUTOFFS_HZ:
            ax.axvline(cutoff, linestyle=":", linewidth=0.8)
        ax.set_xlim(20, FS / 2)
        ax.set_ylim(-75, 15)
        ax.set_xlabel("Frequência (Hz)")
        ax.set_ylabel("Magnitude (dB)")
        ax.set_title("Respostas em frequência dos cinco filtros FIR")
        ax.grid(which="both", alpha=0.25)
        ax.legend(fontsize=8, ncol=2, loc="lower left")
        fig.tight_layout()
        return fig

    def export_transfer_figure(self) -> None:
        path_text = filedialog.asksaveasfilename(
            title="Salvar gráfico de respostas em frequência",
            defaultextension=".png",
            initialfile="respostas_frequencia_equalizador.png",
            filetypes=[("PNG", "*.png"), ("PDF", "*.pdf")],
        )
        if not path_text:
            return
        try:
            fig = self._build_transfer_figure()
            fig.savefig(path_text, bbox_inches="tight")
            self.status_var.set(f"Gráfico salvo em: {Path(path_text).name}")
        except Exception as exc:
            messagebox.showerror("Erro ao salvar gráfico", str(exc))

    def export_coefficients(self) -> None:
        path_text = filedialog.asksaveasfilename(
            title="Salvar coeficientes FIR",
            defaultextension=".csv",
            initialfile="coeficientes_fir_equalizador.csv",
            filetypes=[("CSV", "*.csv")],
        )
        if not path_text:
            return
        try:
            table = np.column_stack((self.n, self.filters.T))
            header = "n,h_100Hz,h_330Hz,h_1kHz,h_3_3kHz,h_10kHz"
            np.savetxt(path_text, table, delimiter=",", header=header, comments="")
            self.status_var.set(f"Coeficientes FIR salvos em: {Path(path_text).name}")
        except Exception as exc:
            messagebox.showerror("Erro ao salvar coeficientes", str(exc))

    def on_close(self) -> None:
        self.stop()
        self.root.destroy()


def main() -> None:
    if sd is None:
        # A interface ainda abre, mas torna clara a dependência necessária para tocar áudio.
        print("Aviso: sounddevice não está instalado. Use: pip install sounddevice")
    root = tk.Tk()
    EqualizerApp(root)
    root.mainloop()


if __name__ == "__main__":
    main()